version: "3.8"
services:
  app:
    image: node:18.7.0
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: all
    command: "yarn run dev"
